[env:esp32-s3-devkitm-1]
platform  = espressif32
board     = esp32-s3-devkitm-1
framework = arduino

; Velocidad del monitor serie
monitor_speed = 115200

; Opciones de compilación
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM

; Opciones de upload (USB nativo del ESP32-S3)
upload_protocol = esptool